# Create new secrets with:
#   sops secrets/new.yaml

# Add a new host able to decrypt with:
#   nix-shell -p ssh-to-age --run 'cat /etc/ssh/ssh_host_ed25519_key.pub | ssh-to-age'
#
# If you add new hosts use 'updatekeys':
#   sops updatekeys secrets/secrets.yaml

keys:
  - &user_aorith age1ad0yj8p7anrput7cw47j08q76ldf3athn9nt7nf9096pec5dpegqzcftg7
  - &host_trantor age16emq92lnyqs3hyqpzenn4g6996zp8twp5a487r7rwtkgu855recsyrj62c
  - &host_msi age1grp6xvf6z2dggm96zflpdaf3du7y5r2rekyxtwks25xls0r92dpqyrnaqw
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *user_aorith
          - *host_trantor
          - *host_msi
